### ISSUE TITLE
Add support for named shadows

### ISSUE THREAD

**Issue by AshUK** [aws/Device-Shadow-for-AWS-IoT-embedded-sdk#55]
The library currently only supports classic shadow.

Feature request to add support for multiple shadows as define in the [AWS documentation](https://docs.aws.amazon.com/iot/latest/developerguide/device-shadow-mqtt.html).

My preference is for Shadow_MatchTopic and Shadow_GetTopicString to take additional arguments. Which would return the length and position of the named shadow or to add additional APIs Shadow_Named_x.

**Comment by aggarw13** [comment]
Hi @AshUK, thank you for your request. We are working on incorporating the Named Shadow feature within the library in PR #56.

**Comment by aggarw13** [comment]
Hi @AshUK, the library has been updated to support the Named Shadow feature of AWS IoT Device Shadow service. We will be adding a demo in the [aws-iot-device-sdk-embedded-C](https://github.com/aws/aws-iot-device-sdk-embedded-C) repository soon to use the Named Shadow feature with the library.

**Comment by AshUK** [comment]
@gregbreen @aggarw13 thanks very much for the fast turn around on this feature request it is very much appreciated. I have been following the PR. Nice to see a great effort going in to ensure good code quality and code hygiene.
